CLASS zcl_219000_demo_0101 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_oo_adt_classrun .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_219000_demo_0101 IMPLEMENTATION.

  METHOD if_oo_adt_classrun~main.
    out->write( 'Hallo Welt!' ). "Ausgabe
  ENDMETHOD.

ENDCLASS.
